// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — advisory locks used by `migrate deploy`
    // don't work over Neon's pooled/PgBouncer connection. The app itself (src/lib/prisma.ts) still
    // connects at runtime using the pooled DATABASE_URL, which is unaffected by this.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
