-- AlterTable
ALTER TABLE "Fixture" ALTER COLUMN "kickoff" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Prediction" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Round" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);
